variables:
  - template: /eng/pipelines/templates/variables/globals.yml

jobs:
  - job: SmokeTest

    strategy:
      matrix:
        Windows_NetCoreApp (AzureChinaCloud):
          OSVmImage: "windows-2019"
          TestTargetFramework: netcoreapp2.1
          SubscriptionConfiguration: $(sub-config-cn-test-resources)
          ArmTemplateParameters: $(azureChinaCloudArmParameters)
        Windows_NetFramework (AzureChinaCloud):
          OSVmImage: "windows-2019"
          TestTargetFramework: net461
          SubscriptionConfiguration: $(sub-config-cn-test-resources)
          ArmTemplateParameters: $(azureChinaCloudArmParameters)

    pool:
      vmImage: $(OSVmImage)

    variables:
      azureCloudArmParameters: "@{ storageEndpointSuffix = 'core.windows.net'; azureCloud = 'AzureCloud'; }"
      azureUSGovernmentArmParameters: "@{ storageEndpointSuffix = 'core.usgovcloudapi.net'; azureCloud = 'AzureUSGovernment'; }"
      azureChinaCloudArmParameters: "@{ storageEndpointSuffix = 'core.chinacloudapi.cn'; azureCloud = 'AzureChinaCloud'; }"

    steps:
      - template: /eng/common/pipelines/templates/steps/verify-agent-os.yml

      - task: PowerShell@2
        inputs:
          targetType: filePath
          filePath: ./common/SmokeTests/SmokeTest/Update-Dependencies.ps1
          arguments: -CI
          workingDirectory: common/SmokeTests/SmokeTest
          pwsh: true
        displayName: Use latest dev feed package versions

      - pwsh: Get-Content ./common/SmokeTests/SmokeTest/SmokeTest.csproj
        displayName: Show SmokeTest.csproj

      - template: /eng/pipelines/templates/steps/install-dotnet.yml

      - pwsh: dotnet restore ./common/SmokeTests/SmokeTest/SmokeTest.csproj
        displayName: dotnet restore

      - template: /eng/common/TestResources/deploy-test-resources.yml
        parameters:
          ServiceDirectory: '$(Build.SourcesDirectory)/common/SmokeTests/'
          SubscriptionConfiguration: $(SubscriptionConfiguration)
          ArmTemplateParameters: $(ArmTemplateParameters)

      - pwsh: dotnet run -p .\common\SmokeTests\SmokeTest\SmokeTest.csproj --framework $(TestTargetFramework)
        displayName: "Run Smoke Tests"

      - template: /eng/common/TestResources/remove-test-resources.yml
        parameters:
          ServiceDirectory: '$(Build.SourcesDirectory)/common/SmokeTests/'
          SubscriptionConfiguration: $(SubscriptionConfiguration)
